try:
    print(x)
except:
    print("Error occurred")
finally:
    print("success")